name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  WORKSPACE: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download tfvars file from S3
        run: aws s3 cp s3://my-terraform-config-bucket-muna/terraform.tfvars terraform/app/app.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/app

      - name: Select Terraform Workspace
        run: |
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
        working-directory: terraform/app

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var-file="app.tfvars" \
            -var alb_deletion_protection=false
        working-directory: terraform/app

      - name: Summary
        run: echo "### Terraform Apply Completed" >> $GITHUB_STEP_SUMMARY
