name: Terragrunt Destroy (prod)

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

jobs:
  terragrunt-destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::985539771340:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.56.0/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: Terragrunt Init (prod)
        working-directory: terraform/terragrunt/prod
        run: terragrunt init --terragrunt-non-interactive

      - name: Terragrunt Destroy (prod)
        working-directory: terraform/terragrunt/prod
        run: |
          terragrunt destroy \
            --terragrunt-non-interactive \
            -auto-approve \