name: Terragrunt Plan (dev)

on:
  pull_request:
    paths:
      - "terraform/**"
  workflow_run:
    workflows: ["Docker Build & Push"]
    types: [completed]
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

jobs:
  terragrunt-plan:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::985539771340:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Terragrunt
        run: |
          TG_VERSION=0.56.0
          curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: Terragrunt Init (dev)
        working-directory: terraform/terragrunt/dev
        run: terragrunt init --terragrunt-non-interactive

      - name: Terragrunt Format Check
        working-directory: terraform
        run: terraform fmt -check -recursive

      - name: Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          tflint --chdir=terraform/modules

      - name: Install Checkov
        run: pip install checkov==3.2.450

      - name: Run Checkov
        run: |
          checkov -d terraform/modules --quiet --framework terraform \
          --skip-check CKV2_AWS_31,CKV2_AWS_76,CKV_AWS_336,CKV_AWS_150

      - name: Terragrunt Plan (dev)
        working-directory: terraform/terragrunt/dev
        run: terragrunt plan --terragrunt-non-interactive -out=tfplan